name: docker_build

on:
  push:
    branches:
      - "main"
      - "feature/*"
      - "bugfix/*"

env:
  TEST_TAG: jake-fawcett/rust-web-server:test
  LATEST_TAG: jake-fawcett/rust-web-server:latest
  PLATFORMS: linux/arm64, linux/arm64, linux/arm64/v8, linux/amd64

jobs:
  dev-build:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'feature') || contains(github.ref, 'bugfix')
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ghcr.io/${{ env.TEST_TAG }}

  prod-build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ghcr.io/${{ env.LATEST_TAG }}