name: docker_build

on:
  push:
    branches:
      - "main"

env:
  TEST_TAG: Jake-Fawcett/rust-web-app:test
  LATEST_TAG: Jake-Fawcett/rust-web-app:latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Github Container registry
        run: docker push ghcr.io/${{ env.LATEST_TAG }}