name: docker_build

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/Jake-Fawcett/rust-web-app:latest
          docker run ghcr.io/Jake-Fawcett/rust-web-app:latest
          docker push ghcr.io/Jake-Fawcett/rust-web-app:latest