name: docker_build

on:
  push:
    branches:
      - "main"
      - "bugfix/platform-image-issue"

env:
  TEST_TAG: jake-fawcett/rust-web-server:test
  LATEST_TAG: jake-fawcett/rust-web-server:latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64/v8
          push: true
          tags: ghcr.io/${{ env.TEST_TAG }}